#' Check if the query rate limit has been exceeded
#'
#' Check if the query rate limit for the LLM provider has been exceeded. If the
#' rate limit has been exceeded, the function will wait for the specified time
#' before retrying the request.
#'
#' @param response The response object from an LLM calling function.
#' @param wait If `TRUE`, the function will wait for the time specified in the
#'   response error message before retrying the request.
#' @param max_attempts The number of times to retry the request before rising an
#'   error and stopping the process.
#' @param log_request If `TRUE`, the error message from the response will be
#'   printed to the console.
#'
#' @return `TRUE` if the request failed due to rate limiting
#'
is_rate_limit_exceeded <- function(
    response,
    wait = TRUE,
    max_attempts = getOption("llmr_retry_attempts", 3),
    log_request = getOption("llmr_log_request", FALSE)
) {
  failure <- FALSE

  if (httr::status_code(response) == 429) {
    warning("Rate limit exceeded. Waiting before retrying.",
            immediate. = TRUE, call. = FALSE)

    if (log_request) {
      warning(httr::content(response)$error$message,
              immediate. = TRUE, call. = FALSE)
    }

    to_wait <- as.numeric(httr::headers(response)$`retry-after`)

    if (isTRUE(wait)) {
      message("Waiting for ", to_wait, " seconds.\n...")
      Sys.sleep(to_wait)
      message("Retrying...")
    }

    attempt_number <- getOption("llmr_attempt_number", 1)

    options(llmr_attempt_number = attempt_number + 1)

    if (attempt_number > max_attempts) {
      options(llmr_attempt_number = 1)

      stop("Maximum number of attempts (", max_attempts,
           ") on `retry` error reached.")
    }

    failure <- TRUE
  } else {
    options(llmr_attempt_number = 1)
  }

  return(failure)
}

#' Stop on response error
#'
#' Stop the execution of the script if the response object from an LLM calling
#' function contains an error message.
#'
#' @param response The response object from an LLM calling function.
#'
#' @return NULL
stop_on_response_error <- function(response) {

  if (httr::http_error(response)) {
    err_obj <- httr::content(response)$error

    err_message <- if (is.character(err_obj)) {
      err_obj
    } else if (is.character(err_obj$message)) {
      err_obj$message
    } else {
      httr::content(response)
    }

    stop("Error in LLM request: ", err_message)
  } else {
    error_in_content <- purrr::pluck(
      httr::content(response), "error", .default = F)

    if (!isFALSE(error_in_content)) {
      stop("Error in LLM request: ", error_in_content$message)
    }
  }
}

#' Stop if no tokens were generated
#'
#' Stop the execution of the script if no tokens were generated by the LLM
#' provider.
#'
#' @param parsed The parsed response object from an LLM calling function.
#'
#' @return NULL
stop_on_no_output <- function(parsed) {
  if (
    purrr::is_empty(parsed$usage$completion_tokens) ||
    parsed$usage$completion_tokens == 0 ||
    is.null(parsed$usage$completion_tokens)) {

    stop("No tokens were generated.")
  }
}
